name: Sub Protocol
description: "Collective musings on &lt;code&gt;, #devops, {algorithm}, and randomness."
url: http://subprotocol.com/
markdown: kramdown
highlighter: pygments
lsi: false
paginate: 100
permalink: "/system/:title.html"
plugins:
  - jekyll-redirect-from
  - jekyll-paginate